### ISSUE TITLE
FontAwesome icon support

### ISSUE THREAD

**Issue by coatless** [coatless-quarto/custom-callout#1]
Create a mapping taking `fa-*` class and switch it to the unicode value. 

For example, we have `fa-user` would be mapped to `f007`.

CSS rule:

```css
.callout-user > .callout-header::before {
  font-family: "Font Awesome 6 Free";
  content: "\f007";
  margin-right: 5px;
  font-size: 13px;
}
```

This is a better approach for icon inclusion compared to using `quarto-ext/fontawesome` as drops in HTML, e.g. `<i class="fa-user"></i>`. (And, no, you cannot insert an element via `content`.)
